services:
  docs:
    image: my_personal_blog_local_docs
    container_name: my_personal_blog_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./my_personal_blog:/app/my_personal_blog:z
    ports:
      - '9000:9000'
    command: /start-docs
